# -*- coding: utf-8 -*-
"""Belajar Analisis Data dengan Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12aExURwkoHuQhihyvW2Uv-bpbFsfFDSw

# Proyek Analisis Data: Nama dataset
- Nama: Hifdzul Malik
- Email: hifdzulmalik30@gmail.com
- Id Dicoding: hifdzulmalik30

## Menentukan Pertanyaan Bisnis

- pertanyaan 1 : berapa total sewa sepeda untuk tahun 2012 selama musim panas (2) ?

- pertanyaan 2 : Apa pengaruh cuaca (weathersit) terhadap jumlah sewa sepeda (cnt) selama musim semi (1)?

## Menyaipkan semua library yang dibuthkan
"""

import pandas as pd
import plotly.express as px

import warnings

"""## Data Wrangling

### Gathering Data
"""

df_day = pd.read_csv("day.csv")
df_hour = pd.read_csv("hour.csv")

df_day.head()

df_hour.head()

"""### Assessing Data"""

print('Dataframe day:')
print(df_day.info())

print('\nDataframe hour:')
print(df_hour.info())

#missing value
print('Dataframe day:')
print(df_day.isna().sum())

print('\nDataframe hour:')
print(df_hour.isna().sum())

#duplicate data
print('Dataframe day:', df_day.duplicated().sum())
print("Dataframe hour:", df_hour.duplicated().sum())

df_day.describe()

df_hour.describe()

"""### Cleaning Data"""

# df_day
df_day["dteday"] = pd.to_datetime(df_day["dteday"])
# df_hour
df_hour["dteday"] = pd.to_datetime(df_hour["dteday"])

# Check data type for df_day and df_hour
print('df_day["dteday"] : ', df_day["dteday"].dtypes)
print('df_hour["dteday"] : ', df_hour["dteday"].dtypes)

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

warnings.filterwarnings("ignore")

# df_day
correlation_matrix = df_day.corr()
fig = px.imshow(correlation_matrix)
fig.update_layout(title="hubungan antara Variabel Numerik")
fig.show()

numeric_cols = ['temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']
for col in numeric_cols:
    fig = px.histogram(df_day, x=col, title=f'Distribusi {col}')
    fig.show()

categorical_cols = ['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']
for col in categorical_cols:
    fig = px.bar(df_day[col].value_counts().reset_index(), x='index', y=col)
    fig.update_layout(title=f'Distribusi {col}')
    fig.show()

fig = px.box(df_day, x='season', y='cnt')
fig.update_layout(title='Hubungan antara Musim dan Jumlah Sewa')
fig.show()

fig = px.box(df_day, x='holiday', y='cnt')
fig.update_layout(title='Hubungan antara Hari Libur dan Jumlah Sewa')
fig.show()

fig = px.box(df_day, x='weathersit', y='cnt')
fig.update_layout(title='Hubungan antara Cuaca dan Jumlah Sewa')
fig.show()

fig = px.scatter(df_day, x='temp', y='cnt', title='Scatter Plot antara Suhu dan Jumlah Sewa')
fig.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1:  berapa total sewa sepeda untuk tahun 2012 selama musim panas (2) ?
"""

# Filter tahun 2012 dan musim panas (2)
filtered_data = df_day[(df_day["yr"] == 1) & (df_day["season"] == 2)]

# Hitung jumlah total sewa sepeda (cnt)
total_sewa_sepeda = filtered_data["cnt"].sum()

print("Jumlah total sewa sepeda untuk tahun 2012 selama musim panas (2):", total_sewa_sepeda)

"""### Pertanyaan 2: Apa pengaruh cuaca (weathersit) terhadap jumlah sewa sepeda (cnt) selama musim semi (1)?"""

# Filter musim semi (1)
filtered_data = df_day[df_day["season"] == 1]

# Buat plot dengan Plotly untuk menganalisis pengaruh cuaca terhadap jumlah sewa sepeda
fig = px.bar(filtered_data, x="weathersit", y="cnt", title="Pengaruh Cuaca terhadap Jumlah Sewa Sepeda (musim semi)")
fig.update_xaxes(title="Cuaca (weathersit)")
fig.update_yaxes(title="Jumlah Sewa Sepeda (cnt)")

# Tampilkan plot
fig.show()

"""weathersit :

1: Clear, Few clouds, Partly cloudy, Partly cloudy.

2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist.

3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds.

## Conclusion

- Conclution pertanyaan 1 : Faktor cuaca memiliki pengaruh signifikan terhadap jumlah sepeda yang disewa.
- conclution pertanyaan 2 : Hubungan antara suhu dan jumlah pengguna terdaftar penyewaan sepeda menunjukkan bahwa cuaca memengaruhi minat bersepeda, dengan peningkatan suhu cenderung meningkatkan jumlah pengguna.
"""

